baseurl      = "https://gracious-kare-e44b98.netlify.app" # TODO: use a proper domain
title        = "SpiderSwarm"
languageCode = "en-us"
theme        = "hello-friend-ng"
paginate     = 10

[params]
  dateform        = "Jan 2, 2006"
  dateformShort   = "Jan 2"
  dateformNum     = "2006-01-02"
  dateformNumTime = "2006-01-02 15:04"

  # Subtitle for home
  homeSubtitle = "Scalable, cloud-native web scraping framework based on dataflow programming concepts"

  # Set disableReadOtherPosts to true in order to hide the links to other posts.
  disableReadOtherPosts = false

  # Enable sharing buttons, if you like
  enableSharingButtons = true

  # Metadata mostly used in document's head
  description = "Scalable, cloud-native web scraping framework based on dataflow programming concepts"
  keywords = "web scraping, web crawling"
  images = [""]

[languages]
  [languages.en]
    title = "SpiderSwarm"
    subtitle = "A simple theme for Hugo"
    keywords = ""
    copyright = '<a href="https://creativecommons.org/licenses/by-nc/4.0/" target="_blank" rel="noopener">CC BY-NC 4.0</a>'
    readOtherPosts = "Read other posts"

    [languages.en.params.logo]
      logoText = "spsw"
      logoHomeLink = "https://github.com/spiderswarm/spiderswarm"
    # or
    #
    # path = "/img/your-example-logo.svg"
    # alt = "Your example logo alt text"

  # And you can even create generic menu
  #[[menu.main]]
  #  identifier = "blog"
  #  name       = "Blog"
  #  url        = "/posts"
